### ISSUE TITLE
License and certificate question

### ISSUE THREAD

**Issue by andrejohansson** [DIGGSweden/DGCValidator#5]
From what I can see, this repository is using the MIT license model. I just want verify/clarify two things:

1. Is it permitted to make commercial applications from this?
1. Certificates are fetched from urls specified [here](https://github.com/DIGGSweden/DGCValidator/blob/792c3ebfc3f0d695ecfeb788e0397ae3b0b0ac14/DGCValidator/Services/RestService.cs#L156)
    - Are these urls official in some capacity? 
    - Will these be updated if some country revokes their signing certificate and issues a new one?

**Comment by sondaica** [comment]
1. Yes, as long as you follow the MIT license
2. Yes, these are the official Swedish URLs and all certificates are in sync with all DCC countries

**Comment by andrejohansson** [comment]
Thank you for the response!
